### ISSUE TITLE
[BITS] Error on hex values

### ISSUE THREAD

**Issue by derpicknicker1** [j-zero/ConsoleUtils#3]
## What happend
When executing `bits` with a hex color value as parameter the program crashes

## What was expected
Do same conversions as with other numbers (convert DEC to hex color works. Why not the other way)

### ERR Msg
```
Unhandled exception. System.ArgumentException: The number styles AllowHexSpecifier and AllowBinarySpecifier are not supported on floating point data types. (Parameter 'style')
   at System.Globalization.NumberFormatInfo.<ValidateParseStyleFloatingPoint>g__ThrowInvalid|166_0(NumberStyles value)
   at System.Double.TryParse(String s, NumberStyles style, IFormatProvider provider, Double& result)
   at bits.bits.Parse(String data) in D:\a\ConsoleUtils\ConsoleUtils\ConsoleUtils\bits\bits.cs:line 103
   at bits.bits.Main(String[] args) in D:\a\ConsoleUtils\ConsoleUtils\ConsoleUtils\bits\bits.cs:line 79
```

![image](https://github.com/j-zero/ConsoleUtils/assets/5983533/1093c1a4-3823-4566-85ce-93054fa2d689)

**Comment by j-zero** [comment]
fixed.
